[default]
prefix="-"
log_level = "info"
log_file_prefix="./logs/"
core_cogs=['log', 'cogs']

[cogs]
custom=['coc_inorganic', 'anime', 'chem', 'subscribe']
list=['misc', 'gifs', 'music']
acitvity=['ayu', 'midnight', 'tapu', 'zapp']

[server]
guild_id=123
error_log_channel=123
message_log_channel=123
mod_log_channel=123
notification_channel=123

[perms]
cog_ops_access_role=123
bot_admin_ops_role=123