[default]
prefix="-"
log_level = "info"
log_file_prefix="./logs/"
core_cogs=['log', 'cogs']
guild_id=123

[cogs]
custom=['coc_inorganic', 'anime', 'chem']
list=['misc', 'gifs']

[server]
error_log_channel=123
message_log_channel=123
mod_log_channel=123

[perms]
cog_ops_access_role=123