[default]
prefix="-"
log_level = "info"
log_file_prefix="./logs/"
core_cogs=['log', 'cogs']

[cogs]
custom=['coc_inorganic', 'anime']
list=['misc']

[server]
error_log_channel=123
message_log_channel=123
mod_log_channel=123

[perms]
cog_ops_access_role=123